#!/bin/bash

WINEDLLPATH="debian/wineftd2xx/usr/lib/$(arch)-linux-gnu/wine/"
echo "$WINEDLLPATH"
mkdir -p "$WINEDLLPATH"
#ln -s /usr/lib/x86_64-linux-gnu/wine/libwine.so.1 debian/usr/lib/$(arch)-linux-gnu/libwine.so.1
#[ -d "$WINEDLLPATH" ] || exit 1

